Pinterest/config/routes.rb
Rails.application.routes.draw do
	resources :pins, :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root "pins#index"
	get "/new", to: "pins#new"
end

Pinterest/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Pinterest/app/models/pin.rb
class Pin < ApplicationRecord
end

Pinterest/app/models/user.rb
class User < ApplicationRecord
end

Pinterest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Pinterest/app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :find_pin, only: [:show, :edit, :update, :destroy]
	def index
		@pins = Pin.all()
	end
	def show
		@pin = Pin.find(params[:id])
	end


	def new
		@pin = Pin.new
	end

	def create
		@pin = Pin.new(pin_params)
		if @pin.save
			redirect_to @pin, notice: "Success!!"
		else
			render 'new'
		end

	end

	def update
	end

	private
	def pin_params
		params.require(:pin).permit(:description, :title)
	end

	def find_pin
		@pin = Pin.find(params[:id])
	end
end

Pinterest/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new()
	end
	def create
	end

end

Pinterest/app/helpers/application_helper.rb
module ApplicationHelper
end

Pinterest/app/helpers/pins_helper.rb
module PinsHelper
end

Pinterest/app/helpers/users_helper.rb
module UsersHelper
end

Pinterest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Pin clone</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body class="container">
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
	    <%= link_to "Pin", root_path %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

	<%= yield %>
</body>
</html>

Pinterest/app/views/pins/_form.html.haml
= simple_form_for @pin, html: {multipart: true} do |f|
  - if @pin.errors.any?
    #Errors
      %h2 
        = pluralize(@pin.errors.count, "error")
        prevented this pin from saving
        %ul
          - @pin.errors.full_messages.each do |msg|
            %li = msg

  .form-group
    = f.input :title, input_html: { class: 'form-control'}
  .form-group
    = f.input :description, input_html: { class: 'form-control'}

  = f.button :submit, class: 'btn btn-primary'

Pinterest/app/views/pins/index.html.erb
<h1>Welcome to Pinterest clone</h1>

<% @pins.each do |p| %>
<h4><%=link_to p.title, pin_path(p) %></h4>
<% end %>

<p><%= link_to "New pin", new_pin_path %></p>

Pinterest/app/views/pins/index.html.haml
%h1 This is a test file

Pinterest/app/views/pins/new.html.haml
%h1 New pin

= render 'form'
= link_to "Back", root_path

Pinterest/app/views/pins/show.html.erb
<h2><%= @pin.title %> </h2>
<h3><%= @pin.description %></h3>

<%= link_to  "Home", root_path %>

Pinterest/app/views/users/new.html.erb
<h2>Log in</h2>

<%= simple_form_for(@user, as: @user ) do |f| %>
  <div class="form-inputs">
    <%= f.input :email, required: false, autofocus: true %>
    <%= f.input :password, required: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Log in" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

Pinterest/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>